# Generated by Django 3.2.8 on 2022-12-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=256, unique=True)),
                ('request_time', models.CharField(max_length=128)),
                ('request_url', models.CharField(max_length=2048)),
                ('request_ip', models.CharField(max_length=128)),
                ('request_method', models.CharField(max_length=128)),
                ('log_type', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
    ]
