# Generated by Django 3.2.8 on 2022-12-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilogs',
            name='trace_id',
            field=models.CharField(max_length=256),
        ),
    ]
