# Generated by Django 3.2.8 on 2023-01-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0003_loginlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_code', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
                ('class_id', models.CharField(max_length=128)),
                ('school_name', models.CharField(max_length=128)),
                ('school_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=256)),
                ('exam_id', models.CharField(max_length=256)),
                ('subject_name', models.CharField(max_length=256)),
                ('subject_id', models.CharField(max_length=256)),
                ('score', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark.users')),
            ],
        ),
    ]
