# Generated by Django 3.2.8 on 2023-01-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0004_marks_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=128)),
                ('can_get_data', models.BooleanField()),
            ],
        ),
    ]
